
[[constraint]]
  name = "github.com/Clever/analytics-util"
  version = "1.0.0"

[[constraint]]
  name = "github.com/Clever/discovery-go"

[[constraint]]
  name = "github.com/Clever/pathio"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.0"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/Clever/optimus.v3"
  version = "3.7.0"

[[constraint]]
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "v0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pquerna/ffjson"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "^6.15.0"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.1.3"
